### ISSUE TITLE
7 – Create Currency Specific Gold Valuation 

### ISSUE THREAD

**Issue by JuannnHerrera** [BrennanB572/Gold_Price_vs_Inflation#15]
EU – 2steps under each

**Comment by BrennanB572** [comment]
EURO currency eval file uploaded. Next step is to fix data to only show full year 2013->2022

**Comment by BrennanB572** [comment]
https://finance.yahoo.com/quote/EURUSD%3DX/history?p=EURUSD%3DX&guccounter=1

**Comment by ChristianBlomgren** [comment]
Completed and updated.
