### ISSUE TITLE
8 – USA DRAFT - Scatter Plot: (Create a comparison of the gold and currency inflation rate.)

### ISSUE THREAD

**Issue by JuannnHerrera** [BrennanB572/Gold_Price_vs_Inflation#18]
USA –  DRAFT ONLY
Price on Y axis
Time on X Axis
??? on z axis

**Comment by ritikadc** [comment]
I made a graph which is called - US_Currency_Inflation_Plotting_percentages. I gave the US_Inflation_vs_ Gold.ipynb file to Brennan and he pushed it to GitHub for me.

**Comment by JuannnHerrera** [comment]
confirmed complete with brennan and ritika
