### ISSUE TITLE
1 - Complete exports for inflation rates: 

### ISSUE THREAD

**Issue by JuannnHerrera** [BrennanB572/Gold_Price_vs_Inflation#2]
USA 
EUROPE 
RUSSIA 
CHINA

from 
Inflation Rates:
EU
[European Union Inflation Rate (tradingeconomics.com)](https://tradingeconomics.com/european-union/inflation-rate)
 USA
[United States Inflation Rate (tradingeconomics.com)](https://tradingeconomics.com/united-states/inflation-cpi)
China
[China Inflation Rate (tradingeconomics.com)](https://tradingeconomics.com/china/inflation-cpi)
Russia
[Russia Inflation Rate (tradingeconomics.com)](https://tradingeconomics.com/russia/inflation-cpi)

**Comment by BrennanB572** [comment]
Initial API research done and found new links for table requests. 

Will complete USA and Europe CSV file retrieval and upload to the repository

**Comment by BrennanB572** [comment]
Completed.
