### ISSUE TITLE
4 - File Organization

### ISSUE THREAD

**Issue by BrennanB572** [BrennanB572/Gold_Price_vs_Inflation#9]
Come together to ensure all resources files such as CSVs are being stored in one place

**Comment by BrennanB572** [comment]
Please advise if we want to settle on a 'Resources' folder for all excel/resource files. Let me know if this works for ya'll!

**Comment by ritikadc** [comment]
Working on it.

**Comment by BrennanB572** [comment]
Let's circle back on this one. Make sure all csv files are moved to resources or if uploaded they are moved to resources. Thanks ya'll

**Comment by ritikadc** [comment]
I updated my files to Github and also pushed the files to Github.

**Comment by ritikadc** [comment]
Closing issue.
